### PR TITLE
Support full 280 character tweets, plus lots more tweaking of character substitutions/enhancements

### PR DESCRIPTION
**Pull request by ZXGuesser**
Needs the latest version of python-twitter (3.4.1)

### CODE REVIEW

**Comment by mpentler** [comment]
I imagine I’ll take this as-is.

Wondering about making a proper installer for this to check for things like lib upgrades etc. I have no idea how to do things like that though :(

**Comment by ZXGuesser** [comment]
Don't know :(
I've put a guard on the start of a script before to print out a helpful message and exit if a library is missing, but dunno how to do version checking. I'll look into it :)

**Comment by ZXGuesser** [comment]
huh... that's odd. Looks like I am running an older version of the library after all (3.3)

**Comment by mpentler** [comment]
Ok, I think I understand all of this. Taken!

**Pull request merged**
